---
engines:
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- test/**/*
- data/**/*
- lib/softlayer/abuse.rb
- lib/softlayer/abuse/**/*
- lib/softlayer/account.rb
- lib/softlayer/account/**/*
- lib/softlayer/auxiliary.rb
- lib/softlayer/auxiliary/**/*
- lib/softlayer/billing.rb
- lib/softlayer/billing/**/*
- lib/softlayer/brand.rb
- lib/softlayer/brand/**/*
- lib/softlayer/catalyst.rb
- lib/softlayer/catalyst/**/*
- lib/softlayer/compliance.rb
- lib/softlayer/compliance/**/*
- lib/softlayer/configuration.rb
- lib/softlayer/configuration/**/*
- lib/softlayer/container.rb
- lib/softlayer/container/**/*
- lib/softlayer/dns.rb
- lib/softlayer/dns/**/*
- lib/softlayer/event.rb
- lib/softlayer/event/**/*
- lib/softlayer/flexible_credit.rb
- lib/softlayer/flexible_credit/**/*
- lib/softlayer/hardware.rb
- lib/softlayer/hardware/**/*
- lib/softlayer/layout.rb
- lib/softlayer/layout/**/*
- lib/softlayer/locale.rb
- lib/softlayer/locale/**/*
- lib/softlayer/location.rb
- lib/softlayer/location/**/*
- lib/softlayer/marketplace.rb
- lib/softlayer/marketplace/**/*
- lib/softlayer/mc_afee.rb
- lib/softlayer/mc_afee/**/*
- lib/softlayer/metric.rb
- lib/softlayer/metric/**/*
- lib/softlayer/monitoring.rb
- lib/softlayer/monitoring/**/*
- lib/softlayer/network.rb
- lib/softlayer/network/**/*
- lib/softlayer/notification.rb
- lib/softlayer/notification/**/*
- lib/softlayer/product.rb
- lib/softlayer/product/**/*
- lib/softlayer/provisioning.rb
- lib/softlayer/provisioning/**/*
- lib/softlayer/resource.rb
- lib/softlayer/resource/**/*
- lib/softlayer/sales.rb
- lib/softlayer/sales/**/*
- lib/softlayer/scale.rb
- lib/softlayer/scale/**/*
- lib/softlayer/security.rb
- lib/softlayer/security/**/*
- lib/softlayer/service.rb
- lib/softlayer/service/**/*
- lib/softlayer/software.rb
- lib/softlayer/software/**/*
- lib/softlayer/survey.rb
- lib/softlayer/survey/**/*
- lib/softlayer/tag.rb
- lib/softlayer/tag/**/*
- lib/softlayer/ticket.rb
- lib/softlayer/ticket/**/*
- lib/softlayer/user.rb
- lib/softlayer/user/**/*
- lib/softlayer/utility.rb
- lib/softlayer/utility/**/*
- lib/softlayer/virtual.rb
- lib/softlayer/virtual/**/*